### ISSUE TITLE
如何修改样式呢

### ISSUE THREAD

**Issue by zmm2tysu** [liudichen/mui-message#1]
比如把整体高度调低一点

**Comment by liudichen** [comment]
我是新手哈，就自学了一点JS，我只是为了使用方便简单的封装了下notistack这个包。
所以具体应用基本就是要按notistack来。
本身对样式修改的支持有限，就一个classes参数可以修改样式，可以把一些自定义的样式传递到MessageBox的classes 里，比如：
```
import { makeStyles } from '@mui/styles';
import { MessageBox } from 'mui-message';
const useStyles = makeStyles({
   root: {`
    height: 45,
    paddingTop: 0,
    paddingBottom: 0,
  },
});

const App =()=>{
const classes=useStyles();
<>
<Router>
</Router>
  <MessageBox 
     classes={{
       variantSuccess: classes.root,
   }}
  />
</>
}
```
我试了下这样大致可以修改 message.success的样式。可以参考[https://iamhosseindhv.com/notistack/api#classes](https://iamhosseindhv.com/notistack/api#classes)

或者直接写个新的css，把类名传递过去
不知到能不能解决你的问题

**Comment by liudichen** [comment]
另一个方法是传递自定义的content Props给<MessageBox />类似https://iamhosseindhv.com/notistack/demos#custom-snackbar
